version: '3.9'

services:
  db_test:
    image: postgres:15-alpine
    container_name: db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_url_shortener
    ports:
      - "5433:5432"
    networks:
      - test_net

  redis_test:
    image: redis:7-alpine
    container_name: redis_test
    ports:
      - "6380:6379"
    networks:
      - test_net

  test_app:
    build:
      context: .
    container_name: test_app
    depends_on:
      - db_test
      - redis_test
    env_file:
      - .env.test
    command: >
      sh -c "sleep 5 &&
             alembic upgrade head &&
             pytest --disable-warnings --maxfail=1 --tb=short"
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
